#!/usr/bin/env python

import sys, os, subprocess

def usage():
    print 'This will take a PDF and explode it into PNGs'
    print 'Usage:', sys.argv[0], '[filename.pdf]'

if __name__ == '__main__':
    # get input filename
    if len(sys.argv) < 2:
        usage()
        sys.exit()
        
    input_filename = sys.argv[1]

    # validate
    if input_filename[-4:] != '.pdf':
        print "Input filename isn't a PDF"
        sys.exit()

    if not os.path.isfile(input_filename):
        print input_filename, "doesn't exist"
        sys.exit()

    # make dir for pages
    basename = input_filename[:-4]
    pages_dirname = '{0}_pages'.format(basename)
    os.makedirs(pages_dirname, 0700)

    # convert PDF to PNGs
    print 'Converting PDF to PNGs'
    subprocess.call(['convert', '-density', '128', input_filename, '-quality', '100', '-sharpen', '0x1.0', '{0}/{1}-transparent.png'.format(pages_dirname, basename)])

    # flatten all the PNGs, so they don't have transparent backgrounds
    print 'Flattening PNGs'
    filenames = os.listdir(pages_dirname)
    for filename in filenames:
        if filename[-4:] == '.png':
            # one-page exploded PDFs end in "-transparent.png"
            if filename[-16:] == '-transparent.png':
                new_filename = filename.replace('-transparent', '-0')
                subprocess.call(['convert', '{0}/{1}'.format(pages_dirname, filename), '-flatten', '{0}/{1}'.format(pages_dirname, new_filename)])
                os.remove('{0}/{1}'.format(pages_dirname, filename))

            else:
                new_filename = filename.replace('-transparent-', '-')
                subprocess.call(['convert', '{0}/{1}'.format(pages_dirname, filename), '-flatten', '{0}/{1}'.format(pages_dirname, new_filename)])
                os.remove('{0}/{1}'.format(pages_dirname, filename))

    # rename files to sort alphabetically instead of just numerically
    numbers = []
    filenames = os.listdir(pages_dirname)
    filenames.sort()
    filename_template = pages_dirname+'/'+filenames[0].replace('-0.png', '-{0}.png')
    for filename in filenames:
        n = int(filename.split('.png')[0].split('-')[-1])
        numbers.append(n)
    numbers.sort()
    digits = len(str(numbers[-1]))
    for n in numbers:
        cur_digits = len(str(n))
        if cur_digits < digits:
            new_n = '0'*(digits - cur_digits) + str(n)
            os.rename(filename_template.format(n), filename_template.format(new_n))

    print 'All done, now go edit PNGs to redact and then run: pdf-merge', input_filename

